### ISSUE TITLE
Difference between 2 versions (with SQL and remote)?

### ISSUE THREAD

**Issue by ramsestom** [arjunsk/XMPP-Chat-Client-Remote#1]
Hi arjunsk

What are the differences between your two XMPP-chat-client versions exactly. At first I understood that one version was storing the chat history into a local SQLdb whereas the other was retrieving the chat history from the XMPP server each time. But then, on the "remote" version git page I read:

> Note: This requires Chrome Browser inorder to use WebSQL. Chatlogs are maintained in the browsers local SQL db

and

> This is XMPP chat Client build using ionic Cordova. Integrated Local SQL database for storing the chat message 

so this version seems to store chat history into local SQL database too...

So could you please clarify the difference between the two versions?
Thanks

EDIT 
I saw there is actually 4 different versions:

Ionic-Chat-App 
Ionic-XMPP-Chat-Client-with-SQL 
XMPP-Chat-Client-Remote 
XMPP-Chat-Client-Remote2 

but what are the différences between these 4?

**Comment by autoincr** [comment]
Let me clarify it to you.
Ionic Chat App 
       and 
Ionic-XMPP-Chat-Client-with-SQL  **where build for the local server, hosted using Openfire**. Openfire is an XMPP chat server software. I hosted the server on my system and using connectify, i shared this connection among my devices. So i was able to chat among my devices.
And in this, i was not able to setup the new_member_register function. ( I manually registered the new user from Openfire Admin Panel )

By 
XMPP-Chat-Client-Remote
    and
XMPP-Chat-Client-Remote2 

**They are using free remote chat servers** . So you don't have to connect with your local WiFi for accessing the chat . And most importantly the register function was implemented.

**Now what did i mean by WithSQL and   WithoutSQL ?**
WithSQL is using **webSQL which is only available in Chrome**. I have used SQL to save the chat logs.
If you try to run withSQL version on Mozilla, you are most like to get no Outputs because Mozilla is not having WebSQL. And it is most likely that you get some bugs (SQL database not setup )when you port this App version to Android and iOS.

Where as, **WithoutSQL doesn't save any of the chat-logs**(ie we don't use SQL). So you don't get any error. 
 I am directly retrieving the rosters(ie Friends) from the chat server. And if you notice, when ever you open the chat, you will always start with a blank screen,ie no previous messages are shown (where as in WithSQL you can see the previous messages that were saved in SQL DB).
And most importantly you can run it on any browser.
